spring.application.name=compracoletiva
server.port=8080

# Banco de dados H2 persistido em arquivo local
spring.datasource.url=jdbc:h2:file:./compra_coletiva_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=true

# H2 Console Web (acessível em http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Formatação de Datas JSON
spring.jackson.serialization.write-dates-as-timestamps=false
